remote_theme: thelehhman/plainwhite-jekyll
title: Collin Joseph
description: Collin's personal website.

plainwhite:
  name: Collin Joseph
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    linkedIn: in/collin-quintyne/ # format: locale/username
